export const FETCH_ALL_BOOKS = 'FETCH_ALL_BOOKS';
export const FETCH_ALL_BOOKS_SUCCESS = 'FETCH_ALL_BOOKS_SUCCESS';
export const CHANGE_SHELF = 'CHANGE_SHELF';
export const CHANGE_SHELF_SUCCESS = 'CHANGE_SHELF_SUCCESS';
export const SEARCH_BOOKS = 'SEARCH_BOOKS';
export const SEARCH_BOOKS_SUCCESS = 'SEARCH_BOOKS_SUCCESS';
export const CLEAR_SEARCH_RESULT = 'CLEAR_SEARCH_RESULT';
